### ISSUE TITLE
Move placement of this video in curriculum

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/activerecord-associations-video-review-ii#1]
The video in this lesson is more introductory and explanatory than its "review" title suggests. Placing the lesson directly before https://learn.co/tracks/full-stack-web-development/orms-and-activerecord/associations/activerecord-associations and then having the hands on coding lab follow would be much more conducive to learning the material. The previous video, https://learn.co/tracks/full-stack-web-development/orms-and-activerecord/associations/activerecord-associations-video-review could then stay where it is as a reinforcement of the previous lab.

**Comment by curiositypaths** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#3. We will add this to our internal work queue and notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team
