### ISSUE TITLE
Suggest Summary and Objectives

### ISSUE THREAD

**Issue by kyleblee** [learn-co-curriculum/activerecord-associations-video-review-ii#2]
_Suggested Summary_
- In this video, we review the CRUD functionality of Active Record and introduce validations when persisting to the database. We also talk about the nuances of the behavior that parent and child objects take when saving, the importance of paying attention to / predicting return values, and how to hook into various life cycle events via hooks / callbacks.

_Suggested Objectives_
- Discuss Active Record’s CRUD functionality and how it interacts with a database
- Understand why you should avoid overriding methods that Active Record exposes to you or takes care of under the hood (such as, _initialize_ or _attr_accessor_)
- Explain the difference between a PORO (“plain old Ruby object”) and an Active Record object and why that difference is important to understanding what libraries really do in a program (expose methods to your objects)
- Find out which new methods were added to a class in Ruby by subtracting an object without the association from the object with the association in command line
- Quickly identify which object belongs_to another object by looking at which object contains a foreign_key attribute and corresponding table column
- Understand _ActiveRecord::AssociationTypeMismatch_ errors and how they are Active Record trying to protect us from incorrect association implementations by maintaining type
- Memorize that saving a parent object automatically saves all of its children objects (and that you can easily tell which object is the parent object by identifying which object is at the left-most end of the method chain)
- Introduce _rails erd_ and demonstrate how to use it to generate an entity relationship diagram for you, based on your current rails app
- Discuss _builder_ methods and how they allow us to associate a child object to a parent object upon initialization
- Understand that _#create_, in addition to instantiating a new object, also automatically persists that object to database 
- Explain that the _shovel method_ (<<) is actually closer to _#create_ than it is to _#build_ because when you push an object into a collection (using shovel), you are automatically saving / persisting that object to the database
- Define the difference between _#create_ and the _shovel method_ (<<)—_#create_ returns just the object that was created, while the _shovel method_ returns all the object in that collection
- Talk about the various methods that allow Active Record to hook into life cycle events via _callbacks_ (or _hooks_)
- Avoid overriding life cycle events and other methods exposed to you via Active Record
- Remember that the moment in an object’s life cycle when Active Record runs its validation routine on an object is when that object is saved / persisted to the database (or when #valid? is called on that object)
- Use _#validates_ to create validations for specific attributes on specific objects

**Comment by curiositypaths** [comment]
Thank you for submitting your suggested summary and objectives.
