### ISSUE TITLE
Simple Typo "Than" in Disclaimer

### ISSUE THREAD

**Issue by ccklight** [learn-co-curriculum/activerecord-associations-video-review-ii#4]
2nd line of Disclaimer should be the word "then" instead of "than"
********

Disclaimer
This video is meant as optional supplemental material to augment the written curriculum. If you feel you already understand ActiveRecord Associations than you are welcome to skip the video and continue forward. Feel free to come back here if you ever want a review.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
